import { randomUUID } from "node:crypto";

const STATES=new Set(['queued','researching','building','editing','testing','qa','waiting','blocked','retrying','awaiting_approval','complete','failed','canceled']);
const EVENTS=new Set(['delegated','state_changed','tool_started','tool_completed','handoff','artifact','qa_started','qa_passed','qa_failed','blocked','retry','approval_requested','approval_granted','approval_denied','completed','failed','canceled']);
const settled=s=>['complete','failed','canceled'].includes(s);
const now=()=>new Date().toISOString().replace(/\.\d{3}Z$/,'Z');

export function createAgentWorkRoomService(db){
 const insertEvent=db.prepare(`INSERT INTO agent_work_events (id,task_id,event_type,actor,from_actor,to_actor,tool_name,summary,artifact_ref,evidence_ref,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`);
 function event(input){if(!EVENTS.has(input.eventType))throw new Error('invalid_work_event_type');const task=get(input.taskId);if(!task)throw new Error('work_task_not_found');const row={id:randomUUID(),taskId:input.taskId,eventType:input.eventType,actor:input.actor,fromActor:input.fromActor||null,toActor:input.toActor||null,toolName:input.toolName||null,summary:input.summary,artifactRef:input.artifactRef||null,evidenceRef:input.evidenceRef||null,metadataJson:input.metadata?JSON.stringify(input.metadata):null,createdAt:now()};insertEvent.run(row.id,row.taskId,row.eventType,row.actor,row.fromActor,row.toActor,row.toolName,row.summary,row.artifactRef,row.evidenceRef,row.metadataJson,row.createdAt);return row;}
 function create(input){if(!STATES.has(input.state||'queued'))throw new Error('invalid_work_task_state');const id=input.id||randomUUID(),ts=now();db.prepare(`INSERT INTO agent_work_tasks (id,department,title,requested_by,orchestrator,director,lead_agent,specialist_agent,opportunity_id,state,current_action,blocker,approval_required,started_at,updated_at,settled_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.department,input.title,input.requestedBy||'Genaro',input.orchestrator||'Aiden',input.director,input.leadAgent||null,input.specialistAgent||null,input.opportunityId||null,input.state||'queued',input.currentAction||null,input.blocker||null,input.approvalRequired?1:0,ts,ts,settled(input.state||'queued')?ts:null);event({taskId:id,eventType:'delegated',actor:input.orchestrator||'Aiden',fromActor:input.requestedBy||'Genaro',toActor:input.director,summary:`Delegated: ${input.title}`});return get(id);}
 function get(id){const task=db.prepare('SELECT * FROM agent_work_tasks WHERE id=?').get(id);if(!task)return null;return {...task,events:listEvents(id)};}
 function listEvents(taskId){return db.prepare('SELECT * FROM agent_work_events WHERE task_id=? ORDER BY created_at ASC,rowid ASC').all(taskId);}
 function list({opportunityId=null,state=null,limit=100}={}){let sql='SELECT * FROM agent_work_tasks WHERE 1=1',args=[];if(opportunityId){sql+=' AND opportunity_id=?';args.push(opportunityId);}if(state){sql+=' AND state=?';args.push(state);}sql+=' ORDER BY updated_at DESC,rowid DESC LIMIT ?';args.push(Math.min(Math.max(Number(limit)||100,1),250));return db.prepare(sql).all(...args).map(t=>({...t,events:listEvents(t.id)}));}
 function transition(input){if(!STATES.has(input.state))throw new Error('invalid_work_task_state');const task=get(input.taskId);if(!task)throw new Error('work_task_not_found');if(settled(task.state))throw new Error('settled_work_task_is_terminal');const ts=now(),settledAt=settled(input.state)?ts:null;db.prepare('UPDATE agent_work_tasks SET state=?,current_action=?,blocker=?,approval_required=?,updated_at=?,settled_at=? WHERE id=?').run(input.state,input.currentAction||null,input.blocker||null,input.approvalRequired?1:0,ts,settledAt,input.taskId);const type=input.eventType||(input.state==='complete'?'completed':input.state==='failed'?'failed':input.state==='canceled'?'canceled':input.state==='blocked'?'blocked':input.state==='retrying'?'retry':input.state==='awaiting_approval'?'approval_requested':'state_changed');event({taskId:input.taskId,eventType:type,actor:input.actor,summary:input.summary||`${task.state} → ${input.state}`,toolName:input.toolName,artifactRef:input.artifactRef,evidenceRef:input.evidenceRef,metadata:input.metadata});return get(input.taskId);}
 return {create,get,list,event,transition};
}
