/** Operator state endpoints — /api/v1/operator/* */
import { sendJson } from "../response.js";
const MAX_TEXT=4000;
async function readJson(req){const chunks=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));const raw=Buffer.concat(chunks).toString("utf8");if(!raw.trim())return{};return JSON.parse(raw);}
const actorOf=req=>req.pipelineSession?.userId||req.pipelineSession?.subject||"local-operator";
function text(value,field,{required=true,max=MAX_TEXT}={}){const v=value===null||value===undefined?"":String(value).trim();if(!v&&required)throw new BadRequest(`missing_${field}`);if(v.length>max)throw new BadRequest(`${field}_too_long`);return v||null;}
class BadRequest extends Error{constructor(code){super(code);this.code=code;}}
export async function handleOperatorRoutes(req,res,ctx,url,segments){
 const [,resource,id]=segments;const known=["next-actions","notes","checklist","interactions","offers","outreach","transactions","transaction-tasks","acquisition-handoffs","dispositions"];
 if(!known.includes(resource)){sendJson(res,404,{ok:false,error:"not_found"});return true;}
 const isWrite=req.method==="POST";if(!isWrite&&req.method!=="GET"&&req.method!=="HEAD"){sendJson(res,405,{ok:false,error:"method_not_allowed"},{Allow:"GET, HEAD, POST"});return true;}
 if(isWrite&&ctx.config.readOnly===true){sendJson(res,503,{ok:false,error:"read_only"});return true;}
 const repo=ctx.services.operator;if(!repo){sendJson(res,503,{ok:false,error:"operator_state_unavailable"});return true;}
 const opportunityId=url.searchParams.get("opportunityId"),actor=actorOf(req);
 try{
  if(!isWrite){switch(resource){
   case"next-actions":return ok(res,{nextActions:repo.listNextActions(opportunityId||null)});
   case"notes":if(!opportunityId)throw new BadRequest("missing_opportunityId");return ok(res,{notes:repo.listNotes(opportunityId)});
   case"checklist":if(!opportunityId)throw new BadRequest("missing_opportunityId");return ok(res,{checklist:repo.listChecklist(opportunityId)});
   case"interactions":if(!opportunityId)throw new BadRequest("missing_opportunityId");return ok(res,{interactions:repo.listInteractions(opportunityId)});
   case"offers":if(!opportunityId)throw new BadRequest("missing_opportunityId");return ok(res,{offers:repo.listOffers(opportunityId)});
   case"outreach":if(!opportunityId)throw new BadRequest("missing_opportunityId");return ok(res,{communications:repo.listCommunications(opportunityId)});
   case"transactions":if(!opportunityId)throw new BadRequest("missing_opportunityId");if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");return ok(res,{milestones:ctx.services.transactions.listMilestones(opportunityId),readiness:ctx.services.transactions.readiness(opportunityId),risk:ctx.services.transactions.riskReport(opportunityId)});
   case"transaction-tasks":if(!opportunityId)throw new BadRequest("missing_opportunityId");if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");return ok(res,{tasks:ctx.services.transactions.listTasks(opportunityId),readiness:ctx.services.transactions.readiness(opportunityId)});
   case"acquisition-handoffs":if(!opportunityId)throw new BadRequest("missing_opportunityId");if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");return ok(res,{handoffs:ctx.services.transactions.listHandoffs(opportunityId)});
   case"dispositions":if(!opportunityId)throw new BadRequest("missing_opportunityId");if(!ctx.services.dispositions)throw new Error("disposition_workflow_unavailable");return ok(res,{plans:ctx.services.dispositions.list(opportunityId)});
  }}
  const body=await readJson(req);
  switch(resource){
   case"next-actions":{if(id){const updated=repo.completeNextAction({id,actor,status:body.status||"done"});if(!updated){sendJson(res,404,{ok:false,error:"not_found"});return true;}return ok(res,{nextAction:updated});}return ok(res,{nextAction:repo.createNextAction({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),title:text(body.title,"title",{max:300}),details:text(body.details,"details",{required:false}),dueDate:text(body.dueDate,"dueDate",{required:false,max:40}),actor})},201);}
   case"notes":return ok(res,{note:repo.createNote({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),body:text(body.body,"body"),actor})},201);
   case"checklist":return ok(res,{item:repo.setChecklistItem({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),key:text(body.key,"key",{max:100}),label:text(body.label,"label",{max:300}),checked:body.checked===true,actor})});
   case"interactions":return ok(res,{interaction:repo.createInteraction({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),channel:text(body.channel,"channel",{max:40}),direction:text(body.direction,"direction",{max:20}),summary:text(body.summary,"summary"),outcome:text(body.outcome,"outcome",{required:false,max:200}),occurredAt:text(body.occurredAt,"occurredAt",{required:false,max:40}),actor})},201);
   case"offers":{if(id)return ok(res,{offer:repo.decideOffer({offerId:id,action:text(body.action,"action",{max:50}),proposedPrice:body.proposedPrice,strategyType:body.strategyType,earnestMoney:body.earnestMoney,inspectionDays:body.inspectionDays,closingDays:body.closingDays,contingencies:body.contingencies,internalNotes:body.internalNotes,actor})});const oppId=text(body.opportunityId,"opportunityId",{max:200});for(const f of["proposedPrice","earnestMoney","inspectionDays","closingDays"])if(body[f]===undefined||body[f]===null)throw new BadRequest(`missing_${f}`);if(!body.strategyType)throw new BadRequest("missing_strategyType");return ok(res,{offer:repo.prepareOffer({opportunityId:oppId,proposedPrice:body.proposedPrice,strategyType:body.strategyType,earnestMoney:body.earnestMoney,inspectionDays:body.inspectionDays,closingDays:body.closingDays,contingencies:body.contingencies,internalNotes:body.internalNotes,actor})},201);}
   case"outreach":{if(id&&id!=="draft"&&id!=="inbound"){if(segments[3]==="authorize")return ok(res,{communication:repo.authorizeOutreach(id,actor)});if(segments[3]==="send")return ok(res,{communication:repo.attemptSendOutreach(id,actor)});throw new BadRequest("invalid_action");}if(id==="draft")return ok(res,{communication:repo.createOutreachDraft({opportunityId:text(body.opportunityId,"opportunityId"),offerVersionId:text(body.offerVersionId,"offerVersionId",{required:false}),recipientPersonId:text(body.recipientPersonId,"recipientPersonId"),recipientValueSnapshot:text(body.recipientValueSnapshot,"recipientValueSnapshot"),recipientChannel:text(body.recipientChannel,"recipientChannel"),subject:text(body.subject,"subject",{required:false}),contentText:text(body.contentText,"contentText"),templateVersion:text(body.templateVersion,"templateVersion",{required:false}),actor})},201);if(id==="inbound")return ok(res,{communication:repo.receiveInboundCommunication({opportunityId:text(body.opportunityId,"opportunityId"),recipientPersonId:text(body.recipientPersonId,"recipientPersonId"),recipientValueSnapshot:text(body.recipientValueSnapshot,"recipientValueSnapshot"),recipientChannel:text(body.recipientChannel,"recipientChannel"),subject:text(body.subject,"subject",{required:false}),contentText:text(body.contentText,"contentText"),inReplyToCommunicationId:text(body.inReplyToCommunicationId,"inReplyToCommunicationId",{required:false}),actor})},201);throw new BadRequest("invalid_endpoint");}
   case"transactions":{if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");const milestone=ctx.services.transactions.transition({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),action:text(body.action,"action",{max:80}),effectiveAt:text(body.effectiveAt,"effectiveAt",{required:false,max:40}),scheduledClosingAt:text(body.scheduledClosingAt,"scheduledClosingAt",{required:false,max:40}),reason:text(body.reason,"reason",{required:false,max:1000}),details:body.details&&typeof body.details==="object"?body.details:{},actor});return ok(res,{milestone,readiness:ctx.services.transactions.readiness(body.opportunityId)});}
   case"transaction-tasks":{if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");const task=ctx.services.transactions.upsertTask({opportunityId:text(body.opportunityId,"opportunityId",{max:200}),taskKey:text(body.taskKey,"taskKey",{max:120}),category:text(body.category,"category",{max:40}),title:text(body.title,"title",{max:300}),status:text(body.status||"pending","status",{max:30}),requiredForClosing:body.requiredForClosing!==false,requiredForScheduling:body.requiredForScheduling===true,dueAt:text(body.dueAt,"dueAt",{required:false,max:40}),evidenceRef:text(body.evidenceRef,"evidenceRef",{required:false,max:1000}),notes:text(body.notes,"notes",{required:false}),blockerReason:text(body.blockerReason,"blockerReason",{required:false,max:1000}),reason:text(body.reason,"reason",{required:false,max:1000}),actor});return ok(res,{task,readiness:ctx.services.transactions.readiness(body.opportunityId)});}
   case"acquisition-handoffs":{if(!ctx.services.transactions)throw new Error("transaction_workflow_unavailable");if(!id)throw new BadRequest("missing_handoffId");const handoff=ctx.services.transactions.recordHandoffEvent({handoffId:id,eventType:text(body.eventType,"eventType",{max:40}),detail:text(body.detail,"detail",{required:false,max:1000}),externalRef:text(body.externalRef,"externalRef",{required:false,max:500}),occurredAt:text(body.occurredAt,"occurredAt",{required:false,max:40}),actor});return ok(res,{handoff});}
   case"dispositions":{if(!ctx.services.dispositions)throw new Error("disposition_workflow_unavailable");if(!id){const result=ctx.services.dispositions.createPlan({handoffId:text(body.handoffId,"handoffId",{max:200}),reviewId:text(body.reviewId,"reviewId",{max:200}),actor});return ok(res,result,201);}if(segments[3]==="requirements"){const plan=ctx.services.dispositions.verifyRequirement({planId:id,requirementKey:text(body.requirementKey,"requirementKey",{max:120}),evidenceRef:text(body.evidenceRef,"evidenceRef",{max:1000}),note:text(body.note,"note",{required:false,max:1000}),verifiedAt:text(body.verifiedAt,"verifiedAt",{required:false,max:40}),actor});return ok(res,{plan});}const plan=ctx.services.dispositions.recordEvent({planId:id,eventType:text(body.eventType,"eventType",{max:40}),detail:text(body.detail,"detail",{required:false,max:1000}),evidenceRef:text(body.evidenceRef,"evidenceRef",{required:false,max:1000}),externalRef:text(body.externalRef,"externalRef",{required:false,max:500}),occurredAt:text(body.occurredAt,"occurredAt",{required:false,max:40}),actor});return ok(res,{plan});}
  }
  sendJson(res,404,{ok:false,error:"not_found"});return true;
 }catch(err){if(err instanceof BadRequest){sendJson(res,400,{ok:false,error:err.code});return true;}if(err instanceof SyntaxError){sendJson(res,400,{ok:false,error:"invalid_json"});return true;}const workflowErrors=new Set(["opportunity_not_found","active_offer_required","presented_offer_required","negotiation_not_allowed_from_current_stage","acceptance_not_allowed_from_current_stage","executed_contract_required","due_diligence_required","scheduled_closing_at_required","closing_schedule_required","closed_opportunity_cannot_be_lost","invalid_transaction_action","transaction_task_stage_required","invalid_transaction_task_status","blocker_reason_required","waiver_reason_required","closing_task_evidence_required","closing_schedule_readiness_incomplete","closing_readiness_incomplete","acquisition_handoff_not_found","invalid_acquisition_handoff_event","renovation_exit_handoff_not_found","renovation_exit_review_not_found","approved_exit_decision_required","latest_exit_review_required","disposition_plan_not_found","invalid_disposition_event","disposition_blocker_detail_required","disposition_completion_evidence_required","completed_disposition_is_terminal","blocked_disposition_required","invalid_disposition_requirement","disposition_requirement_evidence_required","disposition_requirement_already_verified"]);if(workflowErrors.has(err.message)||err.message.startsWith("disposition_requirements_incomplete:")){sendJson(res,409,{ok:false,error:err.message});return true;}console.error("[operator] request failed");sendJson(res,500,{ok:false,error:"operator_request_failed"});return true;}
}
function ok(res,data,status=200){sendJson(res,status,{ok:true,data});return true;}
